
//AI generated array
export const ZONE_1_STATIONS = [
  "Aldgate",
  "Aldgate East",
  "Angel",
  "Baker Street",
  "Bank",
  "Barbican",
  "Battersea Power Station",
  "Bayswater",
  "Bond Street",
  "Borough",
  "Chancery Lane",
  "Charing Cross",
  "Covent Garden",
  "Earl's Court",
  "Edgware Road",
  "Elephant & Castle",
  "Embankment",
  "Euston",
  "Euston Square",
  "Farringdon",
  "Gloucester Road",
  "Goodge Street",
  "Great Portland Street",
  "Green Park",
  "High Street Kensington",
  "Holborn",
  "Hyde Park Corner",
  "Kennington",
  "King's Cross St Pancras",
  "Knightsbridge",
  "Lambeth North",
  "Lancaster Gate",
  "Leicester Square",
  "Liverpool Street",
  "London Bridge",
  "Mansion House",
  "Marble Arch",
  "Marylebone",
  "Monument",
  "Moorgate",
  "Nine Elms",
  "Notting Hill Gate",
  "Old Street",
  "Oxford Circus",
  "Paddington",
  "Piccadilly Circus",
  "Pimlico",
  "Queensway",
  "Regent's Park",
  "Russell Square",
  "Shoreditch High Street",
  "Sloane Square",
  "South Kensington",
  "Southwark",
  "St James's Park",
  "St Paul's",
  "Temple",
  "Tottenham Court Road",
  "Tower Hill",
  "Victoria",
  "Warren Street",
  "Waterloo",
  "Westminster"
]

export const ALLOWED_MODES = [
  "tube",
  "dlr",
  "overground",
  "elizabeth-line",
  "national-rail"
];

//AI generated array
export const LINE_COLOURS = {
  bakerloo: "#894E24",
  central: "#DC241F",
  circle: "#FFCE00",
  district: "#007229",
  "hammersmith-city": "#F3A9BB",
  jubilee: "#6A7278",
  metropolitan: "#751056",
  northern: "#000000",
  piccadilly: "#0019A8",
  victoria: "#00A0E2",
  "waterloo-city": "#76D0BD",
  dlr: "#00A4A7",
  overground: "#EE7C0E",
  elizabeth: "#6950A1",
  lioness: "#FFA600",
  suffragette: "#00A3E0",
  windrush: "#E21836",
  weaver: "#9B0056",
  mildmay: "#007A33",
  liberty: "#6E6E6E"
};

export const OVERGROUND_LINES = [
  "lioness",
  "suffragette",
  "windrush",
  "weaver",
  "mildmay",
  "liberty"
]
